# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eses',
            fields=[
                ('id_ese', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom_ese', models.CharField(max_length=100, verbose_name='Nom Entreprise')),
                ('adresse_ese', models.CharField(blank=True, max_length=255, verbose_name='Adresse Entreprise')),
                ('abrev_ese', models.CharField(max_length=100, verbose_name='Sigle Entreprise')),
                ('domaine_ese', models.CharField(max_length=255, unique=True, verbose_name='Nom domaine Entreprise')),
                ('description_ese', models.TextField(blank=True, default='Faire une description', null=True, verbose_name='Descriptif Entreprise')),
                ('schema_name', models.CharField(max_length=255, verbose_name='Nom location BD')),
                ('slogan_ese', models.CharField(blank=True, max_length=255, verbose_name='Slogan Entreprise')),
                ('datecreat_ese', models.DateField(default=django.utils.timezone.now, verbose_name='Date création')),
                ('siege_ese', models.CharField(blank=True, max_length=100, verbose_name='Siège Entreprise')),
                ('pays_ese', models.CharField(blank=True, max_length=255, verbose_name='Pays Entreprise')),
                ('email_ese', models.EmailField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Email Entreprise')),
                ('user_admin_ese', models.EmailField(default='admin@admin.com', max_length=100, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Nom admin Entreprise')),
                ('mdp_admin_ese', models.CharField(default='admin', max_length=255, verbose_name='Mot de passe admin')),
                ('siteweb_ese', models.CharField(blank=True, max_length=100, verbose_name='SIte web Entreprise')),
                ('phone1_ese', models.CharField(blank=True, verbose_name='Téléphone 1 entreprise')),
                ('phone2_ese', models.CharField(blank=True, verbose_name='Téléphone 2 entreprise')),
                ('logo_ese', models.ImageField(blank=True, default='logo.jpeg', null=True, upload_to='', verbose_name='Logo Entreprise')),
                ('num_contrib_ese', models.CharField(blank=True, max_length=255, verbose_name='N° contribuable Entreprise')),
                ('statut_ese', models.CharField(choices=[('ACTIF', 'ACTIF'), ('ALERTE ABONNEMENT', 'ALERTE ABONNEMENT')], default='ACTIF', max_length=255, verbose_name='Statut Entreprise')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Newsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ab', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_gen', models.CharField(max_length=255, null=True)),
                ('direction_fonct', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('agence', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('sous_site', models.CharField(blank=True, max_length=255, null=True)),
                ('organigramme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pr', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_pr', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_pr', models.IntegerField(default=0)),
                ('ref_usine', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_pr', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prest', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_prest', models.CharField(max_length=255)),
                ('organe', models.CharField(blank=True, max_length=255, null=True)),
                ('duree_prest', models.IntegerField(default=0)),
                ('montant_prest', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ese', models.CharField(max_length=255)),
                ('code_ese', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementEse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateField(auto_created=True)),
                ('num_abon', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Code Entreprise')),
                ('date_debut', models.DateField()),
                ('mensualite', models.PositiveIntegerField()),
                ('date_fin', models.DateField()),
                ('nbre_man', models.PositiveIntegerField(default=0, verbose_name='Nbre manutention')),
                ('nbre_vl', models.PositiveIntegerField(default=0, verbose_name='Nbre Véhicule Léger')),
                ('nbre_pl1', models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 1')),
                ('nbre_pl2', models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 2')),
                ('nbre_autobus', models.PositiveIntegerField(default=0, verbose_name='Nbre Autobus')),
                ('nbre_gc', models.PositiveIntegerField(default=0, verbose_name='Nbre Engin Génie civil')),
                ('prcent_remise', models.FloatField()),
                ('nusers_dg', models.PositiveIntegerField(default=0, verbose_name='Direction Générale')),
                ('nusers_dop', models.PositiveIntegerField(default=0, verbose_name='Département Opérations')),
                ('nusers_dex', models.PositiveIntegerField(default=0, verbose_name='Département Exploitation')),
                ('nusers_srm', models.PositiveIntegerField(default=0, verbose_name='Service Maintenance')),
                ('nusers_reg', models.PositiveIntegerField(default=0, verbose_name='Région')),
                ('nusers_age', models.PositiveIntegerField(default=0, verbose_name='Agence')),
                ('nusers_ctq', models.PositiveIntegerField(default=0, verbose_name='Centre Technique')),
                ('nusers_site', models.PositiveIntegerField(default=0, verbose_name='Site')),
                ('nusers_gar', models.PositiveIntegerField(default=0, verbose_name='Garage')),
                ('nusers_mag', models.PositiveIntegerField(default=0, verbose_name='Magasinier')),
                ('montant_verse', models.PositiveIntegerField()),
                ('date_next_versement', models.DateField()),
                ('nbre_users', models.PositiveIntegerField(default=0)),
                ('nbre_engins', models.PositiveIntegerField(default=0)),
                ('montant_engins', models.PositiveIntegerField(default=0)),
                ('montant_users', models.PositiveIntegerField(default=0)),
                ('montant_ht', models.PositiveIntegerField(default=0)),
                ('montant_taxe', models.PositiveIntegerField(default=0)),
                ('montant_ttc', models.PositiveIntegerField(default=0)),
                ('montant_restant', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ese_ese', to='Client.clients')),
            ],
        ),
    ]
