# Generated by Django 6.0.5 on 2026-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementese',
            name='mensualite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_engins',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ht',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_restant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_taxe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ttc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_users',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_verse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_autobus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre Autobus'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_engins',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_gc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre Engin Génie civil'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_man',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre manutention'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_pl1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre Poids Lourd 1'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_pl2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre Poids Lourd 2'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_users',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_vl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nbre Véhicule Léger'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_ctq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Centre Technique'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Département Exploitation'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Direction Générale'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dop',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Département Opérations'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_gar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_mag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Magasinier'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_reg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_srm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Service Maintenance'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='prcent_remise',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
