# Generated by Django 6.0.5 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0002_alter_abonnementese_mensualite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementese',
            name='schema_name',
            field=models.CharField(default='rien', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='mensualite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_verse',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_autobus',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Autobus'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_gc',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Engin Génie civil'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre manutention'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_pl1',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 1'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_pl2',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 2'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_vl',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Véhicule Léger'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_age',
            field=models.PositiveIntegerField(default=0, verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_ctq',
            field=models.PositiveIntegerField(default=0, verbose_name='Centre Technique'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dex',
            field=models.PositiveIntegerField(default=0, verbose_name='Département Exploitation'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dg',
            field=models.PositiveIntegerField(default=0, verbose_name='Direction Générale'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_dop',
            field=models.PositiveIntegerField(default=0, verbose_name='Département Opérations'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_gar',
            field=models.PositiveIntegerField(default=0, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_mag',
            field=models.PositiveIntegerField(default=0, verbose_name='Magasinier'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_reg',
            field=models.PositiveIntegerField(default=0, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_site',
            field=models.PositiveIntegerField(default=0, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nusers_srm',
            field=models.PositiveIntegerField(default=0, verbose_name='Service Maintenance'),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='prcent_remise',
            field=models.FloatField(),
        ),
    ]
