# Generated by Django 6.0.5 on 2026-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0003_abonnementese_schema_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_engins',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ht',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_restant',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_taxe',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ttc',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_users',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_engins',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_users',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
