# Generated by Django 6.0.5 on 2026-09-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0004_alter_abonnementese_montant_engins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_engins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ht',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_restant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_taxe',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_ttc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='montant_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_engins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonnementese',
            name='nbre_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
