# Generated by Django 6.0.5 on 2026-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0005_alter_abonnementese_montant_engins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnementese',
            name='nusers_site',
        ),
        migrations.AddField(
            model_name='abonnementese',
            name='nusers_util',
            field=models.PositiveIntegerField(default=0, verbose_name='Utilisateur'),
        ),
    ]
