# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_enreg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('schema_name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Date Enregistrement')),
                ('nom_ese', models.CharField(max_length=255, unique=True, verbose_name='Nom Entreprise')),
                ('schema_sigle', models.CharField(max_length=255, unique=True, verbose_name='Sigle Entreprise')),
                ('nom_domaine', models.CharField(default='localhost', max_length=255, unique=True, verbose_name='Nom Domaine Entreprise')),
                ('code_ab', models.CharField(max_length=5)),
                ('description_ese', models.TextField(blank=True, default='Faire une description', null=True, verbose_name='Description Entreprise')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Email Entreprise')),
                ('siteweb', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site web Entreprise')),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan Entreprise')),
                ('user_admin', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Username admin')),
                ('mdp_admin', models.CharField(max_length=255, verbose_name='Mot de Passe Admin')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Entreprise')),
                ('niu_ese', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIU Entreprise')),
                ('ville_siege', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville Siège')),
                ('pays', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pays Entreprise')),
                ('phone1', models.CharField(blank=True, null=True, verbose_name='N° Telephone 1')),
                ('phone2', models.CharField(blank=True, null=True, verbose_name='N° Telephone 2')),
                ('logo_ese', models.ImageField(blank=True, default='logo.jpeg', null=True, upload_to='logos/', verbose_name='Logo Entreprise')),
                ('ese_activate', models.BooleanField(default=False, verbose_name='Activation Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Prix_soretac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_taxe', models.FloatField(default=0)),
                ('prix_vl', models.PositiveIntegerField(default=0)),
                ('prix_pl1', models.PositiveIntegerField(default=0)),
                ('prix_pl2', models.PositiveIntegerField(default=0)),
                ('prix_man', models.PositiveIntegerField(default=0)),
                ('prix_autobus', models.PositiveIntegerField(default=0)),
                ('prix_gc', models.PositiveIntegerField(default=0)),
                ('prix_udg', models.PositiveIntegerField(default=0)),
                ('prix_udop', models.PositiveIntegerField(default=0)),
                ('prix_udex', models.PositiveIntegerField(default=0)),
                ('prix_usrm', models.PositiveIntegerField(default=0)),
                ('prix_ureg', models.PositiveIntegerField(default=0)),
                ('prix_uage', models.PositiveIntegerField(default=0)),
                ('prix_uctq', models.PositiveIntegerField(default=0)),
                ('prix_usite', models.PositiveIntegerField(default=0)),
                ('prix_ugar', models.PositiveIntegerField(default=0)),
                ('prix_umag', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AbonneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_abon', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Code Entreprise')),
                ('schema_name', models.CharField(default='rien', max_length=255, unique=True)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('mensualite', models.PositiveIntegerField()),
                ('date_fin', models.DateField()),
                ('nbre_man', models.PositiveIntegerField(default=0, verbose_name='Nbre manutention')),
                ('nbre_vl', models.PositiveIntegerField(default=0, verbose_name='Nbre Véhicule Léger')),
                ('nbre_pl1', models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 1')),
                ('nbre_pl2', models.PositiveIntegerField(default=0, verbose_name='Nbre Poids Lourd 2')),
                ('nbre_autobus', models.PositiveIntegerField(default=0, verbose_name='Nbre Autobus')),
                ('nbre_gc', models.PositiveIntegerField(default=0, verbose_name='Nbre Engin Génie civil')),
                ('prcent_remise', models.FloatField()),
                ('nusers_dg', models.PositiveIntegerField(default=0, verbose_name='Direction Générale')),
                ('nusers_dop', models.PositiveIntegerField(default=0, verbose_name='Département Opérations')),
                ('nusers_dex', models.PositiveIntegerField(default=0, verbose_name='Département Exploitation')),
                ('nusers_srm', models.PositiveIntegerField(default=0, verbose_name='Service Maintenance')),
                ('nusers_reg', models.PositiveIntegerField(default=0, verbose_name='Région')),
                ('nusers_age', models.PositiveIntegerField(default=0, verbose_name='Agence')),
                ('nusers_ctq', models.PositiveIntegerField(default=0, verbose_name='Centre Technique')),
                ('nusers_site', models.PositiveIntegerField(default=0, verbose_name='Site')),
                ('nusers_gar', models.PositiveIntegerField(default=0, verbose_name='Garage')),
                ('nusers_mag', models.PositiveIntegerField(default=0, verbose_name='Magasinier')),
                ('montant_verse', models.PositiveIntegerField()),
                ('date_next_versement', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('ese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ese_abonne', to='Client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='Client.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
