# Generated by Django 6.0.5 on 2026-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prix_soretac',
            old_name='prix_usite',
            new_name='prix_uutil',
        ),
        migrations.RemoveField(
            model_name='abonneclient',
            name='nusers_site',
        ),
        migrations.AddField(
            model_name='abonneclient',
            name='nusers_util',
            field=models.PositiveIntegerField(default=0, verbose_name='Utilisateur'),
        ),
    ]
