# Generated by Django 6.0.5 on 2026-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerte', models.CharField(blank=True, choices=[('0', '0'), ('250 H', '250 H'), ('500 H', '500 H'), ('750 H', '750 H'), ('1000 H', '1000 H'), ('1250 H', '1250 H'), ('1500 H', '1500 H'), ('1750 H', '1750 H'), ('2000 H', '2000 H'), ('5000 KM', '5000 KM'), ('10000 KM', '10000 KM'), ('15000 KM', '15000 KM'), ('20000 KM', '20000 H'), ('25000 KM', '25000 KM'), ('30000 KM', '30000 KM'), ('150 H', '150 H'), ('300 H', '300 H'), ('450 H', '450 H'), ('600 H', '600 H'), ('750 H', '750 H'), ('900 H', '900 H'), ('1050 H', '1050 H'), ('1200 H', '1200 H')], default='0', max_length=50, verbose_name='Alerte')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message')),
                ('compt', models.FloatField()),
                ('type_alert', models.CharField(blank=True, choices=[('A VIDANGER', 'A VIDANGER'), ('EN DEPASSEMENT', 'EN DEPASSEMENT'), ('EN DEPASSEMENT DANGER', 'EN DEPASSEMENT DANGER'), ('EN DEPASSEMENT CRITIQUE', 'EN DEPASSEMENT CRITIQUE')], default='A VIDANGER', max_length=50)),
                ('date_alert', models.DateTimeField(auto_now_add=True)),
                ('ecart', models.FloatField(blank=True, default=0.0, null=True)),
                ('nbalert', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(blank=True, choices=[('EN ATTENTE', 'EN ATTENTE'), ('EN DEMANDE', 'EN DEMANDE'), ('EFFECTUEE', 'EFFECTUEE')], default='EN ATTENTE', max_length=50)),
                ('session_alert', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_compt', models.FloatField(null=True)),
                ('last_compt', models.FloatField(null=True)),
                ('compt_act', models.FloatField(null=True)),
                ('date_compt', models.DateTimeField(auto_now_add=True)),
                ('ecart', models.FloatField(null=True)),
                ('statut_compt', models.CharField(choices=[('EP', 'EP'), ('USUEL', 'USUEL')], default='USUEL', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CountCritique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_count', models.DateTimeField(auto_now_add=True)),
                ('n_depassement', models.PositiveIntegerField()),
                ('n_danger', models.PositiveIntegerField()),
                ('n_critique', models.PositiveIntegerField()),
                ('ecart', models.FloatField()),
                ('statut', models.CharField(choices=[('OUVERT', 'OUVERT'), ('FERME', 'FERME')], default='OUVERT', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CptAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbalert', models.PositiveIntegerField()),
                ('ecart', models.FloatField()),
                ('date_alert', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
