# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompteurApps', '0001_initial'),
        ('Entreprise', '0001_initial'),
        ('MatRoulant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteep',
            name='destinataires',
            field=models.ManyToManyField(blank=True, related_name='alertep_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerteep',
            name='site_fonct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_site_fonct', to='Entreprise.organigramme'),
        ),
        migrations.AddField(
            model_name='alerteep',
            name='site_matrlt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_site_matrlt', to='Entreprise.organigramme'),
        ),
        migrations.AddField(
            model_name='alerteep',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MatRoulant.vehiculeseses'),
        ),
        migrations.AddField(
            model_name='compteurs',
            name='releveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compteurs',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_compteur', to='MatRoulant.vehiculeseses'),
        ),
        migrations.AddField(
            model_name='countcritique',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_critique', to='MatRoulant.vehiculeseses'),
        ),
        migrations.AddField(
            model_name='cptalert',
            name='alertep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_cpt', to='CompteurApps.alerteep'),
        ),
    ]
