# Generated by Django 6.0.5 on 2026-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompteurApps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteurs',
            name='statut_compt',
            field=models.CharField(choices=[('USUEL', 'USUEL'), ('EP', 'EP')], default='USUEL', max_length=15),
        ),
    ]
