# Generated by Django 6.0.5 on 2026-09-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompteurApps', '0003_alter_compteurs_statut_compt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerteep',
            name='site_fonct',
        ),
        migrations.RemoveField(
            model_name='alerteep',
            name='site_matrlt',
        ),
        migrations.AddField(
            model_name='alerteep',
            name='chef_smrlt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_matrlt', to=settings.AUTH_USER_MODEL),
        ),
    ]
