# Generated by Django 6.0.5 on 2026-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompteurApps', '0004_remove_alerteep_site_fonct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcritique',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countcritique',
            name='type_ep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alerteep',
            name='alerte',
            field=models.CharField(blank=True, choices=[('0', '0'), ('250 H', '250 H'), ('500 H', '500 H'), ('750 H', '750 H'), ('1000 H', '1000 H'), ('1250 H', '1250 H'), ('1500 H', '1500 H'), ('1750 H', '1750 H'), ('2000 H', '2000 H'), ('5000 KM', '5000 KM'), ('10000 KM', '10000 KM'), ('15000 KM', '15000 KM'), ('20000 KM', '20000 H'), ('25000 KM', '25000 KM'), ('30000 KM', '30000 KM'), ('40000 KM', '40000 KM'), ('50000 KM', '50000 KM'), ('60000 KM', '60000 KM'), ('150 H', '150 H'), ('300 H', '300 H'), ('450 H', '450 H'), ('600 H', '600 H'), ('750 H', '750 H'), ('900 H', '900 H'), ('1050 H', '1050 H'), ('1200 H', '1200 H')], default='0', max_length=50, verbose_name='Alerte'),
        ),
    ]
