# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
        ('MatRoulant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_dt', models.CharField(blank=True, max_length=100, null=True)),
                ('type_ep', models.CharField(blank=True, max_length=255, null=True)),
                ('compt_alert', models.FloatField()),
                ('date_recept', models.DateField(auto_now_add=True)),
                ('date_ep', models.DateField(null=True)),
                ('compt_ep', models.FloatField(null=True)),
                ('etat_ep', models.CharField(choices=[('EFFECTUE', 'EFFECTUE'), ('NON EFFECTUE', 'NON EFFECTUE')], default='NON EFFECTUE', max_length=20)),
                ('observation', models.TextField()),
                ('garagiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garagiste_eps', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_eps', to='MatRoulant.vehiculeseses')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_ep', models.CharField(blank=True, choices=[('EFFECTUE', 'EFFECTUE'), ('EN ATTENTE', 'EN ATTENTE'), ('EN DEMANDE', 'EN DEMANDE')], max_length=50, null=True)),
                ('dernier_ep', models.CharField(blank=True, max_length=50, null=True)),
                ('comptlast_ep', models.FloatField()),
                ('datelast_ep', models.DateField(blank=True, null=True)),
                ('compt_act', models.FloatField()),
                ('compt_cible', models.FloatField()),
                ('ecart', models.FloatField()),
                ('type_alert', models.CharField(blank=True, max_length=255, null=True)),
                ('prochain_ep', models.CharField(blank=True, max_length=50, null=True)),
                ('statut_dt', models.CharField(blank=True, max_length=100, null=True)),
                ('session_alerte', models.CharField(blank=True, max_length=255, null=True)),
                ('site_fonct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_site_fonct', to='Entreprise.organigramme')),
                ('site_matrlt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_site_matrlt', to='Entreprise.organigramme')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_suiviep', to='MatRoulant.vehiculeseses')),
            ],
        ),
    ]
