# Generated by Django 6.0.5 on 2026-09-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreventApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiviep',
            name='site_fonct',
        ),
    ]
