# Generated by Django 6.0.5 on 2026-09-03 15:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MatRoulant', '0001_initial'),
        ('PreventApps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entete', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=3)),
                ('statut', models.CharField(default='valide', max_length=20)),
                ('suffix', models.CharField(default='000', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DTPrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dtep', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('date_depo', models.DateField(default=datetime.date(2026, 9, 3))),
                ('statut_dt', models.CharField(choices=[('En Demande', 'En Demande'), ('En Cours', 'En Cours'), ('Réalisé', 'Réalisé'), ('Réalisé Partiel', 'Réalisé Partiel'), ('Non Réalisé', 'Non Réalisé'), ('abandonné', 'abandonné')], default='En Demande', max_length=50)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('document_dtep', models.FileField(blank=True, null=True, upload_to='demandes_travaux/')),
                ('priorite', models.CharField(choices=[('NORMAL', 'NORMAL'), ('URGENT', 'URGENT'), ('TRES URGENT', 'TRES URGENT')], default='NORMAL', max_length=50)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dt_exp', to=settings.AUTH_USER_MODEL)),
                ('ep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dt_eps', to='PreventApps.suiviep')),
                ('garagiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dt_dest', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_dt', to='MatRoulant.vehiculeseses')),
            ],
        ),
        migrations.CreateModel(
            name='VehDepoEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateTimeField(auto_created=True)),
                ('depot_utilisateur', models.CharField(choices=[('PAS DEPOSE', 'PAS DEPOSE'), ('DEPOSE', 'DEPOSE')], default='PAS DEPOSE', max_length=20, verbose_name='DEPOT UTILISATEUR')),
                ('observation_util', models.TextField(blank=True, null=True)),
                ('signature_util', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('dtep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depo_dtep', to='Travaux.dtprev')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depo_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehRecuEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recept', models.DateTimeField(auto_created=True)),
                ('valid_garage', models.CharField(choices=[('NON RECU', 'NON RECU'), ('RECU', 'RECU')], default='NON RECU', max_length=20, verbose_name='DEPOT GARAGE')),
                ('observation_gar', models.TextField(blank=True, null=True)),
                ('signature_gar', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('dtep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recu_dtep', to='Travaux.dtprev')),
                ('garagiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recu_garage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
