# Generated by Django 6.0.5 on 2026-09-04 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtprev',
            name='date_depo',
            field=models.DateField(default=datetime.date(2026, 9, 4)),
        ),
    ]
