# Generated by Django 6.0.5 on 2026-09-15 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travaux', '0007_fcmncomarche_fcmncomoteur_fcmnelec_fcmnessieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtcurative',
            name='date_depo',
            field=models.DateField(default=datetime.date(2026, 9, 15)),
        ),
        migrations.AlterField(
            model_name='dtprev',
            name='date_depo',
            field=models.DateField(default=datetime.date(2026, 9, 15)),
        ),
    ]
