# Generated by Django 6.0.5 on 2026-09-16 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travaux', '0008_alter_dtcurative_date_depo_alter_dtprev_date_depo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtcurative',
            name='date_depo',
            field=models.DateField(default=datetime.date(2026, 9, 16)),
        ),
        migrations.AlterField(
            model_name='dtprev',
            name='date_depo',
            field=models.DateField(default=datetime.date(2026, 9, 16)),
        ),
    ]
