# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('matricule', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('CHEF GARAGE', 'CHEF GARAGE'), ('OPERATEUR', 'OPERATEUR'), ('CHEF FONCTIONNEL', 'CHEF FONCTIONNEL'), ('MASTER DATA', 'MASTER DATA'), ('DIRECTEUR GENERAL', 'DIRECTEUR GENERAL'), ('UTILISATEUR', 'UTILISATEUR'), ('MAGASINIER', 'MAGASINIER'), ('CHEF MATERIEL ROULANT', 'CHEF MATERIEL ROULANT'), ('DIRECTEUR MATERIEL ROULANT', 'DIRECTEUR MATERIEL ROULANT')], default='Master Data', max_length=50)),
                ('poste', models.CharField(blank=True, max_length=255, null=True)),
                ('date_nais', models.DateField(blank=True, help_text='Format: JJ-MM-AAAA', null=True)),
                ('genre', models.CharField(blank=True, choices=[('FEMININ', 'FEMININ'), ('MASCULIN', 'MASCULIN')], max_length=50)),
                ('matrimonial', models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, default='user3.png', null=True, upload_to='avatars')),
                ('permis', models.CharField(blank=True, max_length=255, null=True)),
                ('num_cni', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='Document')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_account', to='Entreprise.organigramme')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
