# Generated by Django 6.0.5 on 2026-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF GARAGE', 'CHEF GARAGE'), ('DIRECTEUR GENERAL', 'DIRECTEUR GENERAL'), ('UTILISATEUR', 'UTILISATEUR'), ('MASTER DATA', 'MASTER DATA'), ('CHEF FONCTIONNEL', 'CHEF FONCTIONNEL'), ('DIRECTEUR MATERIEL ROULANT', 'DIRECTEUR MATERIEL ROULANT'), ('CHEF MATERIEL ROULANT', 'CHEF MATERIEL ROULANT'), ('OPERATEUR', 'OPERATEUR'), ('MAGASINIER', 'MAGASINIER')], default='Master Data', max_length=50),
        ),
    ]
