# Generated by Django 6.0.5 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0002_alter_useraccount_genre_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('FEMININ', 'FEMININ'), ('MASCULIN', 'MASCULIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('OPERATEUR', 'OPERATEUR'), ('CHEF FONCTIONNEL', 'CHEF FONCTIONNEL'), ('CHEF GARAGE', 'CHEF GARAGE'), ('MASTER DATA', 'MASTER DATA'), ('UTILISATEUR', 'UTILISATEUR'), ('MAGASINIER', 'MAGASINIER'), ('DIRECTEUR MATERIEL ROULANT', 'DIRECTEUR MATERIEL ROULANT'), ('CHEF MATERIEL ROULANT', 'CHEF MATERIEL ROULANT'), ('DIRECTEUR GENERAL', 'DIRECTEUR GENERAL')], default='Master Data', max_length=50),
        ),
    ]
