# Generated by Django 6.0.5 on 2026-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0003_alter_useraccount_genre_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF FONCTIONNEL', 'CHEF FONCTIONNEL'), ('MAGASINIER', 'MAGASINIER'), ('CHEF MATERIEL ROULANT', 'CHEF MATERIEL ROULANT'), ('CHEF GARAGE', 'CHEF GARAGE'), ('OPERATEUR', 'OPERATEUR'), ('MASTER DATA', 'MASTER DATA'), ('DIRECTEUR GENERAL', 'DIRECTEUR GENERAL'), ('UTILISATEUR', 'UTILISATEUR'), ('DIRECTEUR MATERIEL ROULANT', 'DIRECTEUR MATERIEL ROULANT')], default='Master Data', max_length=50),
        ),
    ]
