# Generated by Django 6.0.5 on 2026-09-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0004_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('UTILISATEUR', 'UTILISATEUR'), ('DIRECTEUR GENERAL', 'DIRECTEUR GENERAL'), ('DIRECTEUR MATERIEL ROULANT', 'DIRECTEUR MATERIEL ROULANT'), ('CHEF FONCTIONNEL', 'CHEF FONCTIONNEL'), ('CHEF MATERIEL ROULANT', 'CHEF MATERIEL ROULANT'), ('MASTER DATA', 'MASTER DATA'), ('OPERATEUR', 'OPERATEUR'), ('MAGASINIER', 'MAGASINIER'), ('CHEF GARAGE', 'CHEF GARAGE')], default='Master Data', max_length=50),
        ),
    ]
