# Generated by Django 6.0.5 on 2026-09-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0006_alter_useraccount_genre_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('MAGASINIER', 'MAGASINIER'), ('CHEF_CTECH', 'CHEF_CTECH'), ('GARAGISTE', 'GARAGISTE'), ('CHEF_REGION', 'CHEF_REGION'), ('DIR_GEN', 'DIR_GEN'), ('DIR_OPER', 'DIR_OPER'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('UTILISATEUR', 'UTILISATEUR'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('CHEF_SITE', 'CHEF_SITE'), ('CHEF_AGENCE', 'CHEF_AGENCE')], default='Master Data', max_length=50),
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_groupusers', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groupusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
