# Generated by Django 6.0.5 on 2026-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0007_alter_useraccount_type_groupusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF_AGENCE', 'CHEF_AGENCE'), ('CHEF_SITE', 'CHEF_SITE'), ('CHEF_REGION', 'CHEF_REGION'), ('GARAGISTE', 'GARAGISTE'), ('MAGASINIER', 'MAGASINIER'), ('DIR_OPER', 'DIR_OPER'), ('MASTER_DATA', 'MASTER_DATA'), ('UTILISATEUR', 'UTILISATEUR'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_CTECH', 'CHEF_CTECH')], default='Master Data', max_length=50),
        ),
    ]
