# Generated by Django 6.0.5 on 2026-09-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0008_alter_useraccount_genre_alter_useraccount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='document',
            new_name='signature',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('FEMININ', 'FEMININ'), ('MASCULIN', 'MASCULIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF_SITE', 'CHEF_SITE'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('MASTER_DATA', 'MASTER_DATA'), ('MAGASINIER', 'MAGASINIER'), ('CHEF_REGION', 'CHEF_REGION'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('GARAGISTE', 'GARAGISTE'), ('CHEF_CTECH', 'CHEF_CTECH'), ('DIR_GEN', 'DIR_GEN'), ('DIR_OPER', 'DIR_OPER'), ('UTILISATEUR', 'UTILISATEUR')], default='Master Data', max_length=50),
        ),
    ]
