# Generated by Django 6.0.5 on 2026-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0009_rename_document_useraccount_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('MAGASINIER', 'MAGASINIER'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('UTILISATEUR', 'UTILISATEUR'), ('CHEF_CTECH', 'CHEF_CTECH'), ('MASTER_DATA', 'MASTER_DATA'), ('DIR_GEN', 'DIR_GEN'), ('GARAGISTE', 'GARAGISTE'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('CHEF_REGION', 'CHEF_REGION'), ('CHEF_SITE', 'CHEF_SITE')], default='Master Data', max_length=50),
        ),
    ]
