# Generated by Django 6.0.5 on 2026-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0010_alter_useraccount_genre_alter_useraccount_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('CHEF_CTECH', 'CHEF_CTECH'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('UTILISATEUR', 'UTILISATEUR'), ('GARAGISTE', 'GARAGISTE'), ('MAGASINIER', 'MAGASINIER'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_SITE', 'CHEF_SITE'), ('CHEF_REGION', 'CHEF_REGION'), ('MASTER_DATA', 'MASTER_DATA')], default='Master Data', max_length=50),
        ),
    ]
