# Generated by Django 6.0.5 on 2026-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0011_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('FEMININ', 'FEMININ'), ('MASCULIN', 'MASCULIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'CELIBATAIRE'), ('MARIE', 'MARIE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF_SMRLT', 'CHEF_SMRLT'), ('UTILISATEUR', 'UTILISATEUR'), ('CHEF_CTECH', 'CHEF_CTECH'), ('DIR_GEN', 'DIR_GEN'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('MASTER_DATA', 'MASTER_DATA'), ('CHEF_REGION', 'CHEF_REGION'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_SITE', 'CHEF_SITE'), ('GARAGISTE', 'GARAGISTE'), ('MAGASINIER', 'MAGASINIER')], default='Master Data', max_length=50),
        ),
    ]
