# Generated by Django 6.0.5 on 2026-09-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0012_alter_useraccount_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('UTILISATEUR', 'UTILISATEUR'), ('GARAGISTE', 'GARAGISTE'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('DIR_GEN', 'DIR_GEN'), ('MASTER_DATA', 'MASTER_DATA'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_REGION', 'CHEF_REGION'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('CHEF_SITE', 'CHEF_SITE'), ('MAGASINIER', 'MAGASINIER'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('CHEF_CTECH', 'CHEF_CTECH')], default='Master Data', max_length=50),
        ),
    ]
