# Generated by Django 6.0.5 on 2026-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0013_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('DIR_OPER', 'DIR_OPER'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_REGION', 'CHEF_REGION'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('CHEF_CTECH', 'CHEF_CTECH'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('UTILISATEUR', 'UTILISATEUR'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('MASTER_DATA', 'MASTER_DATA'), ('MAGASINIER', 'MAGASINIER'), ('CHEF_SITE', 'CHEF_SITE'), ('GARAGISTE', 'GARAGISTE')], default='Master Data', max_length=50),
        ),
    ]
