# Generated by Django 6.0.5 on 2026-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0014_alter_useraccount_matrimonial_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'CELIBATAIRE'), ('MARIE', 'MARIE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('MAGASINIER', 'MAGASINIER'), ('CHEF_REGION', 'CHEF_REGION'), ('CHEF_SITE', 'CHEF_SITE'), ('MASTER_DATA', 'MASTER_DATA'), ('CHEF_CTECH', 'CHEF_CTECH'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('UTILISATEUR', 'UTILISATEUR'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('GARAGISTE', 'GARAGISTE')], default='Master Data', max_length=50),
        ),
    ]
