# Generated by Django 6.0.5 on 2026-09-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0015_alter_useraccount_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF_SMRLT', 'CHEF_SMRLT'), ('CHEF_CTECH', 'CHEF_CTECH'), ('GARAGISTE', 'GARAGISTE'), ('MASTER_DATA', 'MASTER_DATA'), ('UTILISATEUR', 'UTILISATEUR'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('MAGASINIER', 'MAGASINIER'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_SITE', 'CHEF_SITE'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_REGION', 'CHEF_REGION')], default='Master Data', max_length=50),
        ),
    ]
