# Generated by Django 6.0.5 on 2026-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0016_alter_useraccount_matrimonial_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('FEMININ', 'FEMININ'), ('MASCULIN', 'MASCULIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('DIR_GEN', 'DIR_GEN'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('MAGASINIER', 'MAGASINIER'), ('CHEF_SMRLT', 'CHEF_SMRLT'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('CHEF_REGION', 'CHEF_REGION'), ('MASTER_DATA', 'MASTER_DATA'), ('CHEF_SITE', 'CHEF_SITE'), ('CHEF_CTECH', 'CHEF_CTECH'), ('UTILISATEUR', 'UTILISATEUR'), ('DIR_OPER', 'DIR_OPER'), ('GARAGISTE', 'GARAGISTE')], default='Master Data', max_length=50),
        ),
    ]
