# Generated by Django 6.0.5 on 2026-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0017_alter_useraccount_genre_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'CELIBATAIRE'), ('MARIE', 'MARIE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CHEF_REGION', 'CHEF_REGION'), ('CHEF_CTECH', 'CHEF_CTECH'), ('MAGASINIER', 'MAGASINIER'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('GARAGISTE', 'GARAGISTE'), ('DIR_OPER', 'DIR_OPER'), ('MASTER_DATA', 'MASTER_DATA'), ('CHEF_SITE', 'CHEF_SITE'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('UTILISATEUR', 'UTILISATEUR'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_SMRLT', 'CHEF_SMRLT')], default='Master Data', max_length=50),
        ),
    ]
