# Generated by Django 6.0.5 on 2026-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgpaUsers', '0018_alter_useraccount_matrimonial_alter_useraccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='genre',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='matrimonial',
            field=models.CharField(blank=True, choices=[('MARIE', 'MARIE'), ('CELIBATAIRE', 'CELIBATAIRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(blank=True, choices=[('MASTER_DATA', 'MASTER_DATA'), ('CHEF_REGION', 'CHEF_REGION'), ('DIR_OPER', 'DIR_OPER'), ('CHEF_SITE', 'CHEF_SITE'), ('MAGASINIER', 'MAGASINIER'), ('DIR_EXPLOIT', 'DIR_EXPLOIT'), ('UTILISATEUR', 'UTILISATEUR'), ('GARAGISTE', 'GARAGISTE'), ('CHEF_AGENCE', 'CHEF_AGENCE'), ('CHEF_CTECH', 'CHEF_CTECH'), ('DIR_GEN', 'DIR_GEN'), ('CHEF_SMRLT', 'CHEF_SMRLT')], default='Master Data', max_length=50),
        ),
    ]
