# Generated by Django 6.0.5 on 2026-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamComptAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code_ese', models.CharField(blank=True, max_length=250, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicule', models.CharField(blank=True, max_length=255, null=True)),
                ('alert', models.DecimalField(blank=True, decimal_places=1, max_digits=10)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_art', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_art', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_art', models.IntegerField()),
                ('ref_usine', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_art', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestatons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prest', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_prest', models.CharField(max_length=255)),
                ('organe', models.CharField(blank=True, max_length=255, null=True)),
                ('duree_prest', models.IntegerField()),
                ('montant_prest', models.IntegerField()),
            ],
        ),
    ]
