# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssurVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='ASSUREUR')),
                ('date', models.CharField(blank=True, null=True, verbose_name='DATE')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='TYPE')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='MONTANT')),
                ('duree', models.CharField(blank=True, max_length=255, null=True, verbose_name='DUREE')),
                ('date_fin', models.CharField(blank=True, max_length=255, null=True, verbose_name='DATE FIN')),
            ],
        ),
        migrations.CreateModel(
            name='CGVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCE')),
                ('date', models.CharField(blank=True, null=True, verbose_name='DATE')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='MONTANT')),
                ('date_fin', models.CharField(blank=True, max_length=255, null=True, verbose_name='DATE FIN')),
            ],
        ),
        migrations.CreateModel(
            name='VisiteVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCE')),
                ('centre', models.CharField(blank=True, max_length=255, null=True, verbose_name='CENTRE TECHNIQUE')),
                ('date', models.CharField(blank=True, null=True, verbose_name='DATE')),
                ('resultat', models.CharField(blank=True, max_length=255, null=True, verbose_name='RESULTAT')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='MONTANT')),
                ('date_fin', models.CharField(blank=True, max_length=255, null=True, verbose_name='DATE FIN')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculesEses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parc', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° PARC')),
                ('immat', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IMMATRICULATION')),
                ('typecompteur', models.CharField(blank=True, choices=[('HORAIRE', 'HORAIRE'), ('KILOMETRIQUE', 'KILOMETRIQUE')], max_length=50, verbose_name='Unite compteur')),
                ('categorie', models.CharField(blank=True, choices=[('PL1', 'POIDS LOURD 1GEN'), ('PL2', 'POIDS LOURD 2GEN'), ('VL', 'VEHICULE LEGER'), ('MN', 'MANUTENTION')], max_length=100, null=True, verbose_name='CATEGORIE')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='TYPE')),
                ('marque', models.CharField(blank=True, max_length=50, null=True, verbose_name='MARQUE')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODEL')),
                ('energie', models.CharField(blank=True, choices=[('ESSENCE', 'ESSENCE'), ('DIESEL', 'DIESEL'), ('GAZ', 'GAZ'), ('ELECTRIQUE', 'ELECTRIQUE')], max_length=50, null=True, verbose_name='ENERGIE')),
                ('puissance', models.CharField(blank=True, max_length=20, null=True, verbose_name='PUISSANCE')),
                ('serie', models.CharField(blank=True, max_length=255, null=True, verbose_name='N° SERIE')),
                ('branding', models.CharField(blank=True, max_length=255, null=True, verbose_name='BRANDING')),
                ('date_mse', models.CharField(blank=True, null=True, verbose_name='DATE DE SERVICE')),
                ('statut', models.CharField(blank=True, choices=[('EN SERVICE', 'EN SERVICE'), ('EN MAINTENANCE', 'EN MAINTENANCE'), ('EN REFORMATION', 'EN REFORMATION'), ('LITIGIEUX', 'LITIGIEUX'), ('HORS SERVICE', 'HORS SERVICE'), ('SINISTRE', 'SINISTRE'), ('EN EP', 'EN EP')], default='En SERVICE', max_length=50, verbose_name='STATUT')),
                ('identite', models.CharField(blank=True, max_length=255, null=True, verbose_name='IDENTITE')),
                ('affectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='Entreprise.organigramme')),
            ],
        ),
    ]
