# Generated by Django 6.0.5 on 2026-09-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprise', '0001_initial'),
        ('MatRoulant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculeseses',
            name='conducteurs',
            field=models.ManyToManyField(blank=True, related_name='veh_conducteurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculeseses',
            name='site_fonct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_site_fonct', to='Entreprise.organigramme'),
        ),
        migrations.AddField(
            model_name='vehiculeseses',
            name='site_matrlt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_site_matrlt', to='Entreprise.organigramme'),
        ),
        migrations.AddField(
            model_name='cgveh',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartegrise', to='MatRoulant.vehiculeseses'),
        ),
        migrations.AddField(
            model_name='assurveh',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veh_assurance', to='MatRoulant.vehiculeseses'),
        ),
        migrations.AddField(
            model_name='visiteveh',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veh_visitech', to='MatRoulant.vehiculeseses'),
        ),
    ]
