# Generated by Django 6.0.5 on 2026-09-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatRoulant', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculeseses',
            name='site_fonct',
        ),
        migrations.RemoveField(
            model_name='vehiculeseses',
            name='site_matrlt',
        ),
    ]
