# Generated by Django 6.0.5 on 2026-09-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0006_remove_abonnementese_nusers_site_and_more'),
        ('MatRoulant', '0003_remove_vehiculeseses_site_fonct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculeseses',
            name='site_fonct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_site_fonct', to='Entreprise.organigramme'),
        ),
        migrations.AddField(
            model_name='vehiculeseses',
            name='site_matrlt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veh_site_matrlt', to='Entreprise.organigramme'),
        ),
    ]
