# Generated by Django 6.0.5 on 2026-09-09 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatRoulant', '0004_vehiculeseses_site_fonct_vehiculeseses_site_matrlt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculeseses',
            name='site_fonct',
        ),
    ]
